#!/usr/bin/python

import os

"""
print("Path at terminal when executing this file")
print(os.getcwd() + "\n")

print("This file path, relative to os.getcwd()")
print(__file__ + "\n")

print("This file full path (following symlinks)")
full_path = os.path.realpath(__file__)
print(full_path + "\n")

print("This file directory and name")
path, file = os.path.split(full_path)
print(path + ' --> ' + file + "\n")

print("This file directory only")
print(os.path.dirname(full_path))
"""

def list_files_recursively(path):
    # Returns a list of names (with extension, path relative to specified path)
    # of all files in all subdirectories in context folder.
    # Hidden files and folders will be skipped.
    files = []
    excluded_types = ["jpg", "png", "ico", "jpeg", "mp3", "mp4", "ogg"]
    for name in os.listdir(path):
        fullpath = os.path.join(path, name)
        if os.path.isfile(fullpath):
            if name.split(".")[-1] in excluded_types or name[0] == ".":
                continue
            files.append(name)
        else:
            if name[0] != ".":
                subfiles = list_files_recursively(os.path.join(path, name))
                for subfile in subfiles:
                    files.append(os.path.join(name, subfile))
    return files

print list_files_recursively(os.getcwd())

