#!/usr/bin/python

import os
import sys

def list_files_all(path):
  files = []
  for name in os.listdir(path):
    pathname = os.path.join(path, name)
    if name[0] == "." or os.path.islink(pathname):
      continue
    if os.path.isfile(pathname):
      files.append(os.path.relpath(pathname))
    else:
      subfiles = list_files_all(pathname)
      for subfile in subfiles:
        files.append(os.path.relpath(subfile))
  return files

def main():
  files = list_files_all(os.getcwd())
  
  from_text = sys.argv[1]
  to_text = sys.argv[2]
  
  for file in files:
    data = None
    with open(file) as infile:
      data = infile.read()

    data.replace(from_text, to_text)

    with open(file, 'w') as outfile:
      outfile.write(data)

if __name__ == '__main__':
  main()
