#!/usr/bin/python

import argparse
import os

excluded_types = ['jpg', 'png', 'ico', 'jpeg', 'mp3', 'mp4', 'ogg', 'class',
                  'pdf', 'iso', 'msi', 'exe', 'gif']

def list_files(path):
    files = []
    for name in os.listdir(path):
        if name[0] == '.' or name.split('.')[-1] in excluded_types:
            continue
        if os.path.isfile(os.path.join(path, name)):
            files.append(name)
    return files

def list_files_recursively(path):
    files = []
    for name in os.listdir(path):
        if name[0] == '.' or name.split('.')[-1] in excluded_types:
            continue
        if os.path.isfile(os.path.join(path, name)):
            files.append(name)
        else:
            subfiles = list_files_recursively(os.path.join(path, name))
            for subfile in subfiles:
                files.append(os.path.join(name, subfile))
    return files

    
parser = argparse.ArgumentParser(description='Outputs files in the current working directory to the terminal output based on some parameters. If a file or folder is passed in, then this script will list that file and look in the folder for files to list. If no arguments are passed, then the contents of the entire working directory are passed in.')
parser.add_argument('-a', '-all', action='store_true',
                        help='output all hidden and non-hidden files')
parser.add_argument('-r', '-recursive', action='store_true',
                        help='output only non-hidden files')
parser.add_argument('files', nargs='*', default=argparse.SUPPRESS,
                        help='the file to output or folder to look in')
args = parser.parse_args()

filenames = []
if 'files' in vars(args):
    for files in args.files:
        if files[-1] == '/':
            files = files[:-1] 
        fullpath = os.path.join(os.getcwd(), files)
        if not(files in os.listdir(os.getcwd())):
            print files + ' not found, skipping.'
        elif os.path.isfile(fullpath):
            filenames.append(files)
        else:
            if args.a:
                filenames += list_files_all(fullpath)
            elif args.r:
                filenames += list_files_recursively(fullpath)
            else:
                filenames += list_files(fullpath)
elif args.a:
    filenames = list_files_all(os.getcwd())
elif args.r:
    filenames = list_files_recursively(os.getcwd())
else:
    filenames = list_files(os.getcwd())

for filename in filenames:
    print filename
