#!/usr/bin/python

import os
import sys

def list_files_all(path):
    files = []
    for name in os.listdir(path):
        pathname = os.path.join(path, name)
        if name[0] == "." or os.path.islink(pathname):
            continue
        if os.path.isfile(pathname):
            files.append(os.path.relpath(pathname))
        else:
            subfiles = list_files_all(pathname)
            for subfile in subfiles:
                files.append(os.path.relpath(subfile))
    return files

args = sys.argv[1:]

if len(args) == 0:
    for file in list_files_all(os.getcwd()):
        print file
else:
    if (args[0] in os.listdir(os.getcwd()) or args[0][:-1] in os.listdir(os.getcwd())) and not(os.path.isfile(os.path.join(os.getcwd(), args[0]))):
        for file in list_files_all(os.path.join(os.getcwd(), args[0])):
            print file
    else:
        print "Usage:"
        print "lr [subdirectory]"
